// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Infrustructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrustructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Documents.VerificationDocument", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("document_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("VerificationId");

                    b.ToTable("verification_documents", (string)null);

                    b.HasDiscriminator<string>("document_type").HasValue("VerificationDocument");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Domain.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Models.AgentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("role_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AgentRoles", (string)null);

                    b.HasDiscriminator<string>("role_type").HasValue("AgentRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Domain.Models.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("verifications", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Roles.Hostel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.ToTable("Hostels", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Roles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnsurenceDate")
                        .HasColumnType("integer");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductDate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentRoleId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Backend.Infrustructure.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LogInCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogInCodeHash")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PhoneVerificationCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneVerificationCodeHash")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Documents.AddressVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<string>("LocationImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Address");
                });

            modelBuilder.Entity("Backend.Domain.Documents.CarImageVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<string>("CarIdImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<IReadOnlyList<string>>("CarImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.ToTable("verification_documents", t =>
                        {
                            t.Property("IsVerified")
                                .HasColumnName("CarImageVerificationDocument_IsVerified");
                        });

                    b.HasDiscriminator().HasValue("CarImage");
                });

            modelBuilder.Entity("Backend.Domain.Documents.CarInsuranceVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("verification_documents", t =>
                        {
                            t.Property("ExpiryDate")
                                .HasColumnName("CarInsuranceVerificationDocument_ExpiryDate");
                        });

                    b.HasDiscriminator().HasValue("CarInsurance");
                });

            modelBuilder.Entity("Backend.Domain.Documents.EnglishProficiencyVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<string>("CertificateUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasDiscriminator().HasValue("English");
                });

            modelBuilder.Entity("Backend.Domain.Documents.FaceVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<IReadOnlyList<string>>("FaceImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("Face");
                });

            modelBuilder.Entity("Backend.Domain.Documents.IdCardVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdCardImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("IdCard");
                });

            modelBuilder.Entity("Backend.Domain.Documents.TourGuideVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<string>("TourLeaderLicenseImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TourLeader");
                });

            modelBuilder.Entity("DrivingLicenseVerificationDocument", b =>
                {
                    b.HasBaseType("Backend.Domain.Documents.VerificationDocument");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("verification_documents", t =>
                        {
                            t.Property("ExpiryDate")
                                .HasColumnName("DrivingLicenseVerificationDocument_ExpiryDate");
                        });

                    b.HasDiscriminator().HasValue("DrivingLicense");
                });

            modelBuilder.Entity("Backend.Domain.Roles.DriverRole", b =>
                {
                    b.HasBaseType("Backend.Domain.Models.AgentRole");

                    b.HasDiscriminator().HasValue("Driver");
                });

            modelBuilder.Entity("Backend.Domain.Roles.HostRole", b =>
                {
                    b.HasBaseType("Backend.Domain.Models.AgentRole");

                    b.HasDiscriminator().HasValue("Host");
                });

            modelBuilder.Entity("Backend.Domain.Roles.PassengerRole", b =>
                {
                    b.HasBaseType("Backend.Domain.Models.AgentRole");

                    b.HasDiscriminator().HasValue("Passenger");
                });

            modelBuilder.Entity("Backend.Domain.Roles.TourGuideRole", b =>
                {
                    b.HasBaseType("Backend.Domain.Models.AgentRole");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TourGuide");
                });

            modelBuilder.Entity("Backend.Domain.Roles.TranslatorRole", b =>
                {
                    b.HasBaseType("Backend.Domain.Models.AgentRole");

                    b.Property<decimal>("IeltsPoint")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<List<string>>("_languages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Languages");

                    b.HasDiscriminator().HasValue("Translator");
                });

            modelBuilder.Entity("Backend.Domain.Documents.VerificationDocument", b =>
                {
                    b.HasOne("Backend.Domain.Models.Verification", null)
                        .WithOne("Document")
                        .HasForeignKey("Backend.Domain.Documents.VerificationDocument", "VerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Models.Account", b =>
                {
                    b.OwnsMany("Backend.Domain.ValueObjects.Device", "_devices", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OperatingSystem")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("AccountId");

                            b1.ToTable("AccountDevices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AccountId");
                        });

                    b.Navigation("_devices");
                });

            modelBuilder.Entity("Backend.Domain.Models.AgentRole", b =>
                {
                    b.OwnsOne("Backend.Domain.ValueObjects.GeoLocation", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("AgentRoleId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("AgentRoleId");

                            b1.ToTable("AgentRoles");

                            b1.WithOwner()
                                .HasForeignKey("AgentRoleId");
                        });

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("Backend.Domain.Roles.Hostel", b =>
                {
                    b.HasOne("Backend.Domain.Roles.HostRole", null)
                        .WithMany("Hostels")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Backend.Domain.ValueObjects.GeoLocation", "AddressLocation", b1 =>
                        {
                            b1.Property<Guid>("HostelId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Lng");

                            b1.HasKey("HostelId");

                            b1.ToTable("Hostels");

                            b1.WithOwner()
                                .HasForeignKey("HostelId");
                        });

                    b.OwnsOne("Backend.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HostelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Region");

                            b1.HasKey("HostelId");

                            b1.ToTable("Hostels");

                            b1.WithOwner()
                                .HasForeignKey("HostelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AddressLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Roles.Vehicle", b =>
                {
                    b.HasOne("Backend.Domain.Roles.DriverRole", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("AgentRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Infrustructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Infrustructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Infrustructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Infrustructure.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Documents.AddressVerificationDocument", b =>
                {
                    b.OwnsOne("Backend.Domain.ValueObjects.GeoLocation", "GeoLocation", b1 =>
                        {
                            b1.Property<Guid>("AddressVerificationDocumentVerificationId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lat");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("lng");

                            b1.HasKey("AddressVerificationDocumentVerificationId");

                            b1.ToTable("verification_documents");

                            b1.WithOwner()
                                .HasForeignKey("AddressVerificationDocumentVerificationId");
                        });

                    b.Navigation("GeoLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Models.Verification", b =>
                {
                    b.Navigation("Document")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Roles.DriverRole", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Backend.Domain.Roles.HostRole", b =>
                {
                    b.Navigation("Hostels");
                });
#pragma warning restore 612, 618
        }
    }
}
